FROM openjdk:17-alpine

ADD leshan-demo-server-2.0.0-SNAPSHOT-jar-with-dependencies.jar /

EXPOSE 3000 5000 5683 5684 8080 8086

CMD java -jar leshan-demo-server-2.0.0-SNAPSHOT-jar-with-dependencies.jar