{
 "title": "Dashboard",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\") \r\n  |> range(start: -10m) \r\n  |> filter(fn:(r) => r._measurement == \"serverstatus\" and r._field == \"loss\")"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket:\"bucket\") \r\n  |> range(start:-10m) \r\n  |> filter(fn:(r) => r._measurement == \"serverstatus\" and r._field == \"throughput\")"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\") \r\n  |> range(start: -10m) \r\n  |> filter(fn:(r) => r._measurement == \"serverstatus\" and r._field == \"rtt\")"
    }
   ]
  }
 ]
}